### ISSUE TITLE
Take connect-assets to a next level: why the react community fights on webpack vs browserify?

### ISSUE THREAD

**Issue by augnustin** [js-kyle/connect-assets#336]
Hey there,

I'm a JS lover coming from the Rails world. No need to mention that I love the Rails way to handle assets, which directly implies that I love connect-assets too.

Actually, I think it just works _the way it should_.

I'm having a lot of fun with React those days. But I cannot find a decent workflow among those suggested by the React community: should I use webpack, or browserify? My answer to this is clearly connect-assets!

Which brings me to the following question:
#### How come connect-assets isn't so popular in the NodeJS community?

I'm not trying to say the repo badly is managed (course not!) but simply wondering **what are the critics addressed to Sprocket** and consequently connect-assets? What prevented this behavior to become a best practice in app development?

I can't see any reason for having a second process doing a watch on a bunch of files to regenerate something (implying having several consequences on git) instead of simply having a `!= js('application')` one-liner.

Which brings another question:

How could we bring connect-assets to the fighting arena around browserify and webpack. And if we shouldn't, why not ?

Thanks for considering my opinion, and replying in a constructive way!

And thanks a lot for this repo!

**Comment by sahat** [comment]
I am the author of the [Hackathon Starter](https://github.com/sahat/hackathon-starter) and I wanted to add that I too, love the idea of connect-assets. It works like magic without the complexity of adding and maintaining Gulp tasks and Webpack configs.

Unfortunately, I had to switch away from using connect-assets due to poor performance and especially bad start-up times. It was first brought to my attention in https://github.com/sahat/hackathon-starter/issues/247. After digging into it further I posted some timing resutls in https://github.com/sahat/hackathon-starter/issues/317.

This might not matter as much in production after the initial load, but with **nodemon** running in the background and automatically restarting the node process on file changes, those seconds really add up, making dev workflow painfully slow.

**Comment by aug-riedinger** [comment]
Good to hear from you @sahat . I actually found out about connect-assets through Hackathon Starter. Very sweet project by the way!

I'm glad you are giving me a factual reason to not using connect-assets. I hear the argument, though I am quite surprised because:
- I never experienced any slowness there
- this is a non-issue in production since assets are pre-compiled

But I understand this can be a great pain and a NOGO there. Though what is weird then, is that it is actually usable in Ruby/Sprockets, isn't it?
As far as I am concerned, I can't see any major difference between NodeJS and Ruby that would make the feature available in the latter and not in the former, is there?

Any hint from the maintainer here? @adunkman ?
